#!/bin/bash

echo "WARNING: must be run from augur-node root directory"

set +x;
if [[ -z "$CUSTOM_IMAGE_TAG" ]]; then
  # we'll tag off AUGUR_JS_VESRION because that's what upstream does
  IMAGE_TAG="$(npm explore augur.js -- npm run --silent core:version)"
else
  IMAGE_TAG="$CUSTOM_IMAGE_TAG"
fi

docker pull node:8 # ensure latest node image; note this version must correspond to that used in Dockerfile

IMAGE_NAME="stateshape/augur-node" # prefix with stateshape to make clear it's our fork

docker build . -t $IMAGE_NAME:$IMAGE_TAG
